name: Vprofile IAC
on:
  push:
    branches:
      - main
      - stage
    paths:
    - 'terraform/**'        #Trigger workflow only if files in the terraform directory are changed and puhed
  pull_request:
    branches:
      - main
    paths:
    - 'terraform/**'        #Trigger workflow only if files in the terraform directory are changed and puhed and merged to main branch


env:
# Credentials for AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
# S3 nucket for terraform state file
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }} 
  EKS_CLUSTER: vprofile-eks

jobs:
  terraform:
    name: "Apply terraform code changes"
    runs-on: ubuntu-latest                 #runner environment
    defaults:
      run:                                # Sets default options to run steps on bash shell and in the terraform directory
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        #with:
        #  terraform_version: 1.6.3
      
      - name: Terraform Init
        id: init                                      # id to reference outputs of this step if needed
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"       #initialize terraform with s3 backend for state file storage
        working-directory: terraform
      
      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check                #terraform format(fmt) formats the terraform code and  -check to ensure code is formatted properly
        #exit-code: 1                             # exit with code 1 if not formatted properly and fail the workflow
      
      - name: Terraform Validate
        id: validate
        run: terraform validate               # validate the terraform code for syntax errors and other issues
         
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile     # terraform plan gives u info about the changes to be applied and - out to save the plan to a file named planfile and -input=false to disable interactive input and -no-color to disable colored output
        continue-on-error: true                     

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'       # check if the plan step failed
        run: exit 1                                   #exit with code 1 if plan failed. Cancel the workflow
      
     